apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app-deployment
spec:
  selector:
    matchLabels:
      app : echo-app
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app : echo-app
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo
          args:
            - "-text=Welcome To echo App In tap-app-of-apps Repo"