apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: test-selfsigned
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: echo-app-ing
spec:
  rules:
  - host: echoapp.localhost
    http:
      paths:
      - backend:
          serviceName: echo-app-svc
          servicePort: 5678
        path: /   

  tls:
  - hosts:
    - echoapp.localhost
    secretName: echoapp-tls