apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: production
  country: sa

namespace: sealedissuer

resources:
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: localhost:5000/sealedissuer
  newName: localhost:5000/sealedissuer
  newTag: v1